# Genera condiciones.html (ES) + -en/-fr/-ca. Versión v2-2026-10-01
V='v2-2026-10-01'
C={
'es':dict(file='condiciones.html',title='Condiciones generales de reserva',upd='Versión '+V+' · Última actualización: 1 de octubre de 2026',back='Volver al inicio',priv='Política de Privacidad',legal='Aviso Legal',
s=[('1. Titular','<p>MILES · Gastro Cocktail Lounge es un establecimiento explotado por NECTARINE, S.L., CIF B66103920, Carrer de la Diputació, 215 · 08011 Barcelona. Contacto: únicamente por WhatsApp al <a href="https://wa.me/34932472654">+34 932 47 26 54</a> o en events@inconfidencebymiles.com.</p>'),
('2. Solicitud y confirmación','<p>Toda petición enviada desde la web, por WhatsApp o por email es una <b>solicitud de reserva</b> y no constituye una reserva confirmada. La reserva solo queda confirmada cuando la empresa lo comunica expresamente por escrito.</p><p>Cuando se solicita un anticipo, la reserva queda confirmada únicamente tras la recepción efectiva y la verificación del pago por la empresa. La declaración de pago del cliente no constituye, por sí sola, una confirmación definitiva. En caso de pago en efectivo, la reserva queda confirmada únicamente tras el cobro efectivo en el local y la validación del pago por la empresa.</p>'),
('3. Anticipo','<p>El importe del anticipo, la forma de pago (transferencia bancaria o efectivo en el local) y el plazo se indican en la página de pago personal del cliente. Las transferencias deben incluir la referencia indicada. Si el anticipo no se recibe dentro del plazo, la empresa podrá liberar la fecha; ninguna liberación se hace sin decisión de la empresa.</p><p>Por seguridad, la empresa nunca pedirá al cliente cambiar de cuenta bancaria por email ni por mensaje. Ante cualquier duda, el cliente debe contactar únicamente por WhatsApp al +34 932 47 26 54.</p>'),
('4. Número de participantes garantizado','<p>El número de participantes confirmado lors de la reserva constituye el mínimo garantizado y la base de facturación. Si se presentan menos personas, se mantiene el importe correspondiente al número confirmado.</p><p>Salvo que la confirmación de la reserva indique expresamente lo contrario, el número garantizado no puede reducirse. Cuando la confirmación prevé una posibilidad de reducción, esta solo es posible hasta la fecha límite y dentro del mínimo indicados. Fuera de esos casos, cualquier reducción queda sujeta a la aceptación expresa de la empresa.</p><p>Cualquier aumento del número de participantes queda sujeto a disponibilidad, capacidad del espacio y acuerdo por escrito de la empresa.</p>'),
('5. Fórmula tapas + bebida (35 € por persona)','<p>Para esta fórmula se solicita, salvo acuerdo distinto, un anticipo del 50 %. El 50 % restante se abona por transferencia como máximo 48 horas antes del evento, o en efectivo en el local antes de la entrega de los tickets. Los tickets correspondientes a la fórmula se entregan una vez abonado el importe total.</p>'),
('6. Liquidación final','<p>El pago final del evento (saldo y consumiciones adicionales) se realiza de forma agrupada por un máximo de dos personas designadas por el cliente, salvo acuerdo distinto.</p>'),
('7. Cancelación por el cliente','<p>El anticipo es reembolsable si el cliente cancela como muy tarde en la fecha límite indicada en su confirmación. Según el tipo de reserva, el plazo aplicable es: grupo con fórmula de bebidas, 7 días antes del evento; grupo con fórmula de tapas y bebida, 10 días; privatización estándar, 15 días; privatización en fecha de alta demanda, 30 días; condiciones particulares, el plazo pactado por escrito.</p><p>Después del plazo aplicable, o en caso de no presentarse, el anticipo se conserva. La cancelación debe comunicarse por escrito (WhatsApp o email).</p>'),
('8. Cancelación por la empresa','<p>En caso de cancelación por parte de la empresa, las cantidades ya abonadas se reembolsan íntegramente.</p>'),
('9. Datos personales','<p>Los datos facilitados se tratan para gestionar la reserva y el pago, conforme a la <a href="/politica-privacidad">Política de Privacidad</a>.</p>'),
('10. Legislación aplicable','<p>Estas condiciones se rigen por la legislación española, sin perjuicio de los derechos que la normativa de protección de los consumidores reconozca al cliente.</p>')]),
'en':dict(file='condiciones-en.html',title='General booking conditions',upd='Version '+V+' · Last updated: 1 October 2026',back='Back to home',priv='Privacy Policy',legal='Legal Notice',
s=[('1. Operator','<p>MILES · Gastro Cocktail Lounge is operated by NECTARINE, S.L., CIF B66103920, Carrer de la Diputació, 215 · 08011 Barcelona. Contact: WhatsApp only at <a href="https://wa.me/34932472654">+34 932 47 26 54</a> or events@inconfidencebymiles.com.</p>'),
('2. Request and confirmation','<p>Any request sent through the website, WhatsApp or email is a <b>booking request</b> and does not constitute a confirmed booking. A booking is confirmed only when the company expressly confirms it in writing.</p><p>When a deposit is requested, the booking is confirmed only after the payment has actually been received and verified by the company. The customer’s payment declaration alone does not constitute a final confirmation. For cash payments, the booking is confirmed only after the cash has actually been received at the venue and validated by the company.</p>'),
('3. Deposit','<p>The deposit amount, payment method (bank transfer or cash at the venue) and deadline are shown on the customer’s personal payment page. Bank transfers must include the reference provided. If the deposit is not received by the deadline, the company may release the date; no release is made without a decision by the company.</p><p>For security, the company will never ask the customer to change bank account by email or message. If in doubt, contact us on WhatsApp only at +34 932 47 26 54.</p>'),
('4. Guaranteed number of guests','<p>The number of guests confirmed at booking is the guaranteed minimum and the basis for invoicing. If fewer people attend, the amount for the confirmed number still applies.</p><p>Unless the booking confirmation expressly states otherwise, the guaranteed number cannot be reduced. Where the confirmation allows a reduction, it is only possible until the deadline and within the minimum stated. Otherwise, any reduction is subject to the company’s express approval.</p><p>Any increase is subject to availability, capacity and written agreement from the company.</p>'),
('5. Tapas + drinks package (€35 per person)','<p>Unless otherwise agreed, a 50% deposit is requested for this package. The remaining 50% is paid by bank transfer no later than 48 hours before the event, or in cash at the venue before the tickets are handed over. The package tickets are handed over once the full amount has been paid.</p>'),
('6. Final settlement','<p>The final payment for the event (balance and additional drinks) is made together by a maximum of two people designated by the customer, unless otherwise agreed.</p>'),
('7. Cancellation by the customer','<p>The deposit is refundable if the customer cancels no later than the deadline stated in the confirmation. Depending on the type of booking, the applicable deadline is: group with drinks package, 7 days before the event; group with tapas + drinks package, 10 days; standard private hire, 15 days; private hire on a high-demand date, 30 days; special conditions, the deadline agreed in writing.</p><p>After the applicable deadline, or in case of no-show, the deposit is retained. Cancellations must be made in writing (WhatsApp or email).</p>'),
('8. Cancellation by the company','<p>If the company cancels the booking, all amounts already paid are refunded in full.</p>'),
('9. Personal data','<p>Personal data are processed to manage the booking and payment, in accordance with the <a href="/politica-privacidad">Privacy Policy</a>.</p>'),
('10. Applicable law','<p>These conditions are governed by Spanish law, without prejudice to the rights granted to the customer by consumer protection legislation.</p>')]),
'fr':dict(file='condiciones-fr.html',title='Conditions générales de réservation',upd='Version '+V+' · Dernière mise à jour : 1er octobre 2026',back='Retour à l’accueil',priv='Politique de confidentialité',legal='Mentions légales',
s=[('1. Exploitant','<p>MILES · Gastro Cocktail Lounge est exploité par NECTARINE, S.L., CIF B66103920, Carrer de la Diputació, 215 · 08011 Barcelone. Contact : uniquement par WhatsApp au <a href="https://wa.me/34932472654">+34 932 47 26 54</a> ou à events@inconfidencebymiles.com.</p>'),
('2. Demande et confirmation','<p>Toute demande envoyée via le site, WhatsApp ou email est une <b>demande de réservation</b> et ne constitue pas une réservation confirmée. La réservation n’est confirmée que lorsque l’entreprise la confirme expressément par écrit.</p><p>Lorsqu’un acompte est demandé, la réservation est confirmée uniquement après réception effective et vérification du paiement par l’entreprise. La déclaration de paiement du client ne constitue pas, à elle seule, une confirmation définitive. En cas de paiement en espèces, la réservation est confirmée uniquement après encaissement effectif sur place et validation du règlement par l’entreprise.</p>'),
('3. Acompte','<p>Le montant de l’acompte, le moyen de règlement (virement bancaire ou espèces sur place) et l’échéance sont indiqués sur la page de paiement personnelle du client. Les virements doivent comporter la référence indiquée. Si l’acompte n’est pas reçu dans le délai, l’entreprise pourra libérer la date ; aucune libération n’a lieu sans décision de l’entreprise.</p><p>Par sécurité, l’entreprise ne demandera jamais au client de changer de compte bancaire par email ou par message. En cas de doute, contactez-nous uniquement sur WhatsApp au +34 932 47 26 54.</p>'),
('4. Nombre de participants garanti','<p>Le nombre de participants confirmé lors de la réservation constitue le minimum garanti et la base de facturation. Si moins de personnes se présentent, le montant correspondant au nombre confirmé reste applicable.</p><p>Sauf mention expresse contraire dans la confirmation de réservation, le nombre garanti ne peut pas être réduit. Lorsque la confirmation prévoit une possibilité de réduction, celle-ci n’est possible que jusqu’à la date limite et dans la limite du minimum indiqués. En dehors de ces cas, toute réduction est soumise à l’accord exprès de l’entreprise.</p><p>Toute augmentation est soumise à disponibilité, capacité et accord écrit de l’entreprise.</p>'),
('5. Formule tapas + boisson (35 € par personne)','<p>Sauf accord différent, un acompte de 50 % est demandé pour cette formule. Les 50 % restants sont réglés par virement au plus tard 48 heures avant l’événement, ou en espèces sur place avant la remise des tickets. Les tickets de la formule sont remis une fois le montant total réglé.</p>'),
('6. Règlement final','<p>Le règlement final de l’événement (solde et consommations supplémentaires) est effectué de manière groupée par deux personnes au maximum désignées par le client, sauf accord différent.</p>'),
('7. Annulation par le client','<p>L’acompte est remboursable si le client annule au plus tard à la date limite indiquée dans sa confirmation. Selon le type de réservation, le délai applicable est : groupe en formule boissons, 7 jours avant l’événement ; groupe en formule tapas + boisson, 10 jours ; privatisation standard, 15 jours ; privatisation à une date de forte demande, 30 jours ; conditions particulières, le délai convenu par écrit.</p><p>Après le délai applicable, ou en cas de non-présentation, l’acompte est conservé. L’annulation doit être communiquée par écrit (WhatsApp ou email).</p>'),
('8. Annulation par l’entreprise','<p>En cas d’annulation par l’entreprise, les sommes déjà versées sont remboursées intégralement.</p>'),
('9. Données personnelles','<p>Les données sont traitées pour gérer la réservation et le paiement, conformément à la <a href="/politica-privacidad">Politique de confidentialité</a>.</p>'),
('10. Droit applicable','<p>Les présentes conditions sont régies par le droit espagnol, sans préjudice des droits reconnus au client par la réglementation de protection des consommateurs.</p>')]),
'ca':dict(file='condiciones-ca.html',title='Condicions generals de reserva',upd='Versió '+V+' · Darrera actualització: 1 d’octubre de 2026',back='Tornar a l’inici',priv='Política de Privacitat',legal='Avís Legal',
s=[('1. Titular','<p>MILES · Gastro Cocktail Lounge és un establiment explotat per NECTARINE, S.L., CIF B66103920, Carrer de la Diputació, 215 · 08011 Barcelona. Contacte: només per WhatsApp al <a href="https://wa.me/34932472654">+34 932 47 26 54</a> o a events@inconfidencebymiles.com.</p>'),
('2. Sol·licitud i confirmació','<p>Qualsevol petició enviada des del web, per WhatsApp o per email és una <b>sol·licitud de reserva</b> i no constitueix una reserva confirmada. La reserva només queda confirmada quan l’empresa ho comunica expressament per escrit.</p><p>Quan es demana una bestreta, la reserva queda confirmada únicament després de la recepció efectiva i la verificació del pagament per part de l’empresa. La declaració de pagament del client no constitueix, per si sola, una confirmació definitiva. En cas de pagament en efectiu, la reserva queda confirmada únicament després del cobrament efectiu al local i la validació del pagament per part de l’empresa.</p>'),
('3. Bestreta','<p>L’import de la bestreta, la forma de pagament (transferència bancària o efectiu al local) i el termini s’indiquen a la pàgina de pagament personal del client. Les transferències han d’incloure la referència indicada. Si la bestreta no es rep dins del termini, l’empresa podrà alliberar la data; cap alliberament es fa sense decisió de l’empresa.</p><p>Per seguretat, l’empresa mai no demanarà al client canviar de compte bancari per email ni per missatge. En cas de dubte, contacta només per WhatsApp al +34 932 47 26 54.</p>'),
('4. Nombre de participants garantit','<p>El nombre de participants confirmat en fer la reserva constitueix el mínim garantit i la base de facturació. Si es presenten menys persones, es manté l’import corresponent al nombre confirmat.</p><p>Llevat que la confirmació de la reserva indiqui expressament el contrari, el nombre garantit no es pot reduir. Quan la confirmació preveu una possibilitat de reducció, només és possible fins a la data límit i dins del mínim indicats. Fora d’aquests casos, qualsevol reducció queda subjecta a l’acceptació expressa de l’empresa.</p><p>Qualsevol augment queda subjecte a disponibilitat, capacitat i acord per escrit de l’empresa.</p>'),
('5. Fórmula tapes + beguda (35 € per persona)','<p>Per a aquesta fórmula es demana, llevat d’acord diferent, una bestreta del 50 %. El 50 % restant es paga per transferència com a màxim 48 hores abans de l’esdeveniment, o en efectiu al local abans del lliurament dels tiquets. Els tiquets de la fórmula es lliuren un cop pagat l’import total.</p>'),
('6. Liquidació final','<p>El pagament final de l’esdeveniment (saldo i consumicions addicionals) el fan de manera agrupada un màxim de dues persones designades pel client, llevat d’acord diferent.</p>'),
('7. Cancel·lació per part del client','<p>La bestreta és reemborsable si el client cancel·la com a molt tard en la data límit indicada a la seva confirmació. Segons el tipus de reserva, el termini aplicable és: grup amb fórmula de begudes, 7 dies abans de l’esdeveniment; grup amb fórmula de tapes i beguda, 10 dies; privatització estàndard, 15 dies; privatització en data d’alta demanda, 30 dies; condicions particulars, el termini pactat per escrit.</p><p>Després del termini aplicable, o si no es presenta, la bestreta es conserva. La cancel·lació s’ha de comunicar per escrit (WhatsApp o email).</p>'),
('8. Cancel·lació per part de l’empresa','<p>En cas de cancel·lació per part de l’empresa, les quantitats ja abonades es reemborsen íntegrament.</p>'),
('9. Dades personals','<p>Les dades es tracten per gestionar la reserva i el pagament, d’acord amb la <a href="/politica-privacidad">Política de Privacitat</a>.</p>'),
('10. Legislació aplicable','<p>Aquestes condicions es regeixen per la legislació espanyola, sense perjudici dels drets que la normativa de protecció dels consumidors reconegui al client.</p>')])}
C['es']['s'][3]=(C['es']['s'][3][0],C['es']['s'][3][1].replace(' lors de la reserva',' al realizar la reserva'))
import re
css=open('aviso-legal.html').read().split('<style>')[1].split('</style>')[0]
sv=re.search(r'style\.css\?v=\d+',open('aviso-legal.html').read()).group(0)
for k,c in C.items():
    alt=''.join(f'<a href="/{C[x]["file"][:-5]}" hreflang="{x}" lang="{x}">{x.upper()}</a> ' for x in C if x!=k)
    body=''.join(f'<h2>{h}</h2>\n{p}\n' for h,p in c['s'])
    html=f'''<!DOCTYPE html>
<html lang="{k}">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex, follow">
<title>{c['title']} · MILES Gastro Cocktail Lounge</title>
<link rel="stylesheet" href="/{sv}">
<style>{css}  .legal-wrap .langs a {{ margin-right: 10px; }}
</style>
</head>
<body>
<div class="legal-wrap">
<p class="langs">{alt}</p>
<h1>{c['title']}</h1>
<p class="updated">{c['upd']}</p>
{body}
<p style="margin-top: 40px; text-align: center;">
  <a href="/politica-privacidad">{c['priv']}</a> ·
  <a href="/aviso-legal">{c['legal']}</a> ·
  <a href="/">{c['back']}</a>
</p>
</div>
</body>
</html>
'''
    open(c['file'],'w').write(html)
print('ok')
